In [39]:
import pandas as pd
from currency_converter import CurrencyConverter
df = pd.read_csv("jobs.csv")

# Turning all salaries into RON
c = CurrencyConverter()
rates: dict[str, float] = {
	"RON": 1.0,
	"EUR": float(c.convert(1, "EUR", "RON")),
	"USD": float(c.convert(1, "USD", "RON")),
}
rate = df["currency"].map(rates)
df["salary_min_ron"] = df["salary_min"] * rate
df["salary_max_ron"] = df["salary_max"] * rate
df["salary_mid_ron"] = (df["salary_max"] + df["salary_min"]) / 2.00


# turning the string dates of the jobs to actual dates
df["date_posted"] = pd.to_datetime(df["date_posted"], utc=True)
df["valid_through"] = pd.to_datetime(df["valid_through"], utc=True)

# Some jobs are listed like Timisoara (Timis), we split the city and county into 2 different collumns
parts = df["city"].str.split(" (", regex=False, expand=True)
df["city"] = parts[0].str.strip()
df["county"] = parts[2].fillna(parts[1]).str.rstrip(")")

df.head()

,title,company,city,salary_min,salary_max,currency,date_posted,url,employment_type,experience_months,education,industry,occupations,valid_through,description,salary_min_ron,salary_max_ron,salary_mid_ron,county
0,Achizitor auto rulate,TIRIAC AUTO,Constanța,NaN,NaN,NaN,2026-09-17 16:50:20+00:00,https://www.ejobs.ro/user/locuri-de-munca/achi...,FULL_TIME,12.0,"Calificat, Absolvent","Mașini / Auto, Prestări servicii","Achiziții, Auto / Echipamente",2026-10-16 21:00:00+00:00,Ce <strong>responsabilități</strong> vei avea?...,NaN,NaN,NaN,NaN
1,📌Achizitor/Operator,Eurobusiness Tipar,București,NaN,NaN,NaN,2026-08-31 11:19:23+00:00,https://www.ejobs.ro/user/locuri-de-munca/achi...,FULL_TIME,36.0,Absolvent,Producție,Achiziții,2026-09-29 21:00:00+00:00,În rolul de Procurement Specialist / Specialis...,NaN,NaN,NaN,NaN
2,Achizitor Tehnic,Ulma Packaging Production SRL,Cluj-Napoca,NaN,NaN,NaN,2026-08-25 15:38:53+00:00,https://www.ejobs.ro/user/locuri-de-munca/achi...,FULL_TIME,NaN,"Calificat, Absolvent",Producție,"Achiziții, Inginerie, Producție, Specialiști /...",2026-09-23 21:00:00+00:00,<strong>Cerinte:</strong>\n<ul>\n\t<li>Studii ...,NaN,NaN,NaN,NaN
3,ACHIZITOR,SC Global Plast SRL,București,4000.0,6000.0,RON,2026-09-23 09:48:16+00:00,https://www.ejobs.ro/user/locuri-de-munca/achi...,FULL_TIME,36.0,"Calificat, Absolvent","Alimentară, Comerț / Retail, Farma, Transport ...","Achiziții, Administrativ / Logistică, Import -...",2026-10-22 21:00:00+00:00,- Asigurarea disponibilitatii stocurilor pentr...,4000.0,6000.0,5000.0,NaN
4,ADMINISTRATIV/ FINANCIAR CONTABIL,AQUAEDUCT SRL,Arad,3500.0,4000.0,RON,2026-08-26 11:36:06+00:00,https://www.ejobs.ro/user/locuri-de-munca/admi...,FULL_TIME,12.0,Absolvent,Construcții,"Achiziții, Construcții / Instalații, Financiar...",2026-09-24 21:00:00+00:00,<br/>\n<br/>\nEvidență și contabilitate primar...,3500.0,4000.0,3750.0,NaN

In [40]:
df[["city", "county"]].value_counts().head(10)

city        county
Iași        Iași               243
Satu Mare   Satu Mare           53
Bistrița    Bistrița-Năsăud     52
Galați      Galați              50
Târgoviște  Dâmbovița           28
Călărași    Călărași            26
Slatina     Olt                 23
Turda       Cluj                14
Sebeș       Alba                 7
Moreni      Dâmbovița            6
Name: count, dtype: int64

In [ ]:
df[["salary_min_ron", "salary_max_ron", "salary_mid_ron"]].dropna().sample(10)

      salary_min currency  salary_mid_ron
1739      2570.0      RON          2570.0
6166       500.0      EUR          1000.0
2262      3500.0      EUR          4000.0
5499      3000.0      EUR          3000.0
3037      5000.0      RON          7000.0
1481      7000.0      RON          9500.0
1733      4000.0      RON          4500.0
1921      6000.0      RON          6000.0
1381      5000.0      RON          5000.0
942       3000.0      RON          3250.0